// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umchrmsckftmmyfrjycr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtY2hybXNja2Z0bW15ZnJqeWNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMTU0NjAsImV4cCI6MjA2Njc5MTQ2MH0.Zswe4dNT9eYqKuO_0_AYhRikzuOihOmymoxdcOIuuaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);